###
GET http://localhost:8000/ HTTP/1.1

###
POST http://localhost:8000/ HTTP/1.1
Content-Type: application/json

{
        "Image": "ddd",
        "PrecioCosto": 20,
        "Precio": 522,
        "Descripcion": "(aaaa)",
        "Titulo": "aaaaaaaaaaaaaaaaa",
        "banner": "dd"
}

###
DELETE http://localhost:8000/productos/10 HTTP/1.1

###
PUT http://localhost:8000/productos/44 HTTP/1.1
Content-Type: application/json

{
    "Precio": 120.0,
    "Descripcion": "AAAAAAAAA",
    "Titulo": "TITULOOOO"
}